= QML Model list property
In this article we'll take the model we did on the previous articles and projects, and use it with the QQmlListProperty instead of the QList

:toc:
:sectnums:

== Introduction
In this article / chapter, we'll take the `Person`and `PersonModel` we're using all along now, then we'll exposing the list of persons in order to create the persons in the QML side of the application.

NOTE: You will then create an attribute typed with the `QQmlListProperty` and then create make it as a default property in order to feed this list with the QML.

Also, as this `QQmlListProperty` is a property, we need to create the getter and sette of that property as well as the signal to signal all the element that the list has changed.

== List
The list right now is a `QList<Person *>`, now that we are going to use the `QQmlListProperty<Person *>`, in that case, we're going to create some static methods that will be used to:

* Add a person to the list
* Count the number of element present in the list of persons
* Get a single person regarding the index
* Clear the person list

```cpp
class PersonModel : public QAbstractListModel {
    Q_OBJECT
    QML_ELEMENT

    Q_PROPERTY(DataSource *dataSources READ dataSource WRITE setDataSource NOTIFY dataSourceChanged)
    Q_PROPERTY(QQmlListProperty<Person> persons READ persons WRITE setPersons NOTIFY personsChanged)
    Q_CLASSINFO("DefaultProperty", "persons")

    enum {
        NamesRole = Qt::UserRole + 1
        , FavoriteColorRole
        , AgeRole
    };
public:
    explicit PersonModel(QObject *po_parent = nullptr);

    // QAbstractItemModel interface
    int rowCount(const QModelIndex &o_parent) const;
    QVariant data(const QModelIndex &o_idx, int i_role) const;
    QHash<int, QByteArray> roleNames() const;
    Qt::ItemFlags flags(const QModelIndex &o_idx) const;
    bool setData(const QModelIndex &o_idx, const QVariant &o_value, int i_role);

    // Property methods
    DataSource *dataSource() const;
    QQmlListProperty<Person> persons() const;

    void setPersons(const QQmlListProperty<Person> &o_persons);
    void setDataSource(DataSource *po_dataSource);

    // Function to edit the person's object
    bool changePersonsName(Person *po_person, const QString &o_name);
    bool changePersonsFavoriteColor(Person *po_person, const QString &o_favoriteColor);
    bool changePersonsAge(Person *po_person, int i_age);

    // Helper functions
    Q_INVOKABLE void addPerson(const QString &o_name, const QString &o_favoriteColor, const int i_age);
    Q_INVOKABLE void removeLastPerson();

signals:
    void dataSourceChanged();
    void personsChanged(const QQmlListProperty<Person> &o_persons);

private:
    // Methods
    static void appendPerson(QQmlListProperty<Person> *po_persons, Person *po_person);
    static qsizetype personCount(QQmlListProperty<Person> *po_persons);
    static Person *person(QQmlListProperty<Person> *po_person, qsizetype i_idx);
    static void clearPersons(QQmlListProperty<Person> *po_persons);

private:
    DataSource *_po_dataSource;
    bool _b_signalConnected;
    QQmlListProperty<Person> _o_persons;
};
```
Above is an example of the `PersonModel` with the persons in the `QQmlListProperty`. That means we'll be able to do this kind of things inside the QML file:

```qml
persons: [

    Person{
        names: "Daniel Gakwaya"
        favoriteColor: "yellow"
        age : 34
    },
    Person{
        names: "Gwiza Luna"
        favoriteColor: "blue"
        age : 1
    },
    Person{
        names: "Steve Barker"
        favoriteColor: "yellowgreen"
        age : 22
    }

]
```

IMPORTANT: The `persons` array is the `persons` property of type `QQmlListProperty` that is present in the `Q_PROPERTY` in the header of `PersonModel` class.


NOTE: The main things to note in this article, is that we can use default property inside of the header of the Qt model layer in order to use the property inside of the QML to create instances on the fly of the QML file.

The main part of the article is the followings:
````cpp
Q_PROPERTY(QQmlListProperty<Person> persons READ persons WRITE setPersons NOTIFY personsChanged)
Q_CLASSINFO("DefaultProperty", "persons")
```
Below, we are creating a property of type `QQmlListProperty<>`, we create a getter and a setter and then we are using the `Q_CLASSINFO` in order to make use of the `persons` property in the QML directly to initialize it.

IMPORTANT: When you are using the `QQmlListProperty` you shouldn't forget to give it some callback methods to append, get, count and clear the list.